default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: manyo_task_development

test:
  <<: *default
  database: manyo_task_test

production:
  <<: *default
  database: manyo_task_production
  username: manyo_task
  password: <%= ENV['MANYO_TASK_DATABASE_PASSWORD'] %>
